version: "3.6"

services:
#  web:
#    container_name: hacku_vue
#    build: .
#    volumes:
#      - ".:/app"
#    ports:
#      - "8080:8080"
#    tty: true
#    stdin_open: true

   api:
     container_name: hacku_api
     build: ./go
     ports:
       - "3001:3001" # 開放するポート
     volumes:
       - ./go:/app
     tty: true
     # stdin_open: true
     depends_on: # dbコンテナに接続する ビルドするのもdbコンテナが立ち上がってからになる
       - db

   db:
     container_name: hacku_db
     image: mysql:latest
     volumes:
       - ./mysql/mysql_data:/var/lib/mysql # データ永続化のためのボリューム
       - ./mysql/init:/docker-entrypoint-initdb.d
       - ./mysql/conf.d:/etc/mysql/conf.d
     ports:
       - "3036:3036"
     # env_file: ./mysql/.env
     environment:
       TZ: "Asia/Tokyo"
       MYSQL_ROOT_PASSWORD: root
       MYSQL_USER: dev
       MYSQL_PASSWORD: dev
     # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

volumes:
  mysql_data: # ローカルのディレクトリにデータを保存
