
FROM golang:1.15.0-alpine3.12 AS build
# GolangのDockerイメージ取ってくる

ENV GO111MODULE=on

WORKDIR /app

COPY . .

# RUN GOOS=linux GOARCH=amd64 go build main.go
#
# CMD ["./main"]

CMD ["go","run","main.go"]